Enables (limited) continous testing with Travis, fixes #12
- makes sure dependencies install properly
- PEP8 checks
- isort checks
- updates psutils dependency (fixes compilation error on Windows 10)

This is currently in a limited tests probably because we don't have
access to sound services on Travis.
Running `tox -e py36` would return the following error:
```
_ctypes.COMError: (-2147023174, 'The RPC server is unavailable.'...
```