:construction_worker: Migrate to GitHub Actions
Note that we're still not able to run the `tests/test_examples.py` as
the target server probably doesn't have the required hardware.
The error is:
```
======================================================================
ERROR: test_volume_by_process_example (tests.test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\pycaw\pycaw\tests\test_examples.py", line 59, in test_volume_by_process_example
    volume_by_process_example.main()
  File "D:\a\pycaw\pycaw\examples\volume_by_process_example.py", line 8, in main
    sessions = AudioUtilities.GetAllSessions()
  File "D:\a\pycaw\pycaw\pycaw\utils.py", line 189, in GetAllSessions
    mgr = AudioUtilities.GetAudioSessionManager()
  File "D:\a\pycaw\pycaw\pycaw\utils.py", line 177, in GetAudioSessionManager
    speakers = AudioUtilities.GetSpeakers()
  File "D:\a\pycaw\pycaw\pycaw\utils.py", line 159, in GetSpeakers
    EDataFlow.eRender.value, ERole.eMultimedia.value)
_ctypes.COMError: (-2147023728, 'Element not found.', (None, None, None, 0, None))
```